inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

AllCops:
  Exclude:
    - gemfiles/**/*.gemfile
    - gemfiles/vendor/**/*
    - spec/dummy_engine/dummy_engine.gemspec
    - spec/schemas/**/*.rb

  NewCops: enable

Gemspec/RequiredRubyVersion:
  Exclude:
    - 'ros-apartment.gemspec'

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Rails/RakeEnvironment:
  Enabled: false

Rails/ApplicationRecord:
  Enabled: false
