# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
$:.push File.expand_path("../lib", __FILE__)
require "apartment/version"

Gem::Specification.new do |s|
  s.name = %q{apartment}
  s.version = Apartment::VERSION

  s.authors = ["Ryan Brunner", "Brad Robertson"]
  s.date = %q{2011-04-18}
  s.summary = %q{A Ruby gem for managing database multitenancy in Rails applications}
  s.description = %q{Apartment allows Rails applications to deal with database multitenancy}
  s.email = %q{ryan@ryanbrunner.com}
  s.files         = `git ls-files`.split("\n")
  s.test_files    = `git ls-files -- {spec}/*`.split("\n")
  
  s.homepage = %q{http://github.com/ryanbrunner/apartment}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  
  s.add_dependency 'rails', '~> 3.0.7'
  s.add_development_dependency 'rspec', '~> 2.6.0'

end
