#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

cookbook 'apt'
cookbook 'build-essential'
cookbook 'openssl'

cookbook 'postgresql'
cookbook 'mysql'

cookbook 'git'

cookbook 'rvm',
  :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
