name: Rubocop Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ruby:2.6.5

    steps:
    - uses: actions/checkout@v1
    - name: Rubocop Linter
      uses: andrewmcodes/rubocop-linter-action@v2.0.0
      with:
        additional_gems: 'perx-rubocop:0.0.3'
        fail_level: 'warning'
        version: '0.77.0'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
